// <auto-generated />
namespace ElectronicObserver.Window.Integrate
{
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Globalization;
    using System.Reflection;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [SuppressMessage("Microsoft.Design", "CA1053:StaticHolderTypesShouldNotHaveConstructors")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class FormIntegratedRes
    {
        /// <summary>
        /// The resource manager.
        /// </summary>
        private static ResourceManager resourceManager;

        /// <summary>
        /// Initializes a new instance of the <see cref="FormIntegratedRes"/> class.
        /// </summary>
        public FormIntegratedRes()
        {
        }

        /// <summary>
        /// Gets or sets the culture to use for lookups using this strongly typed resource class.
        /// </summary>
        public static CultureInfo CultureInfo { get; set; }

        /// <summary>
        /// Gets the resource string indexed by the IsContains key.
        /// </summary>
        public static string IsContains
        {
            get
            {
                return FormIntegratedRes.ResourceManager.GetString("IsContains", FormIntegratedRes.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the IsEndsWith key.
        /// </summary>
        public static string IsEndsWith
        {
            get
            {
                return FormIntegratedRes.ResourceManager.GetString("IsEndsWith", FormIntegratedRes.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the IsExact key.
        /// </summary>
        public static string IsExact
        {
            get
            {
                return FormIntegratedRes.ResourceManager.GetString("IsExact", FormIntegratedRes.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the resource string indexed by the IsStartsWith key.
        /// </summary>
        public static string IsStartsWith
        {
            get
            {
                return FormIntegratedRes.ResourceManager.GetString("IsStartsWith", FormIntegratedRes.CultureInfo);
            }
        }

        /// <summary>
        /// Gets the cached ResourceManager instance used by this class.
        /// </summary>
        public static ResourceManager ResourceManager
        {
            get
            {
                if (FormIntegratedRes.resourceManager == null)
                {
                    FormIntegratedRes.resourceManager = new ResourceManager("ElectronicObserver.Window.Integrate.FormIntegratedRes", typeof(FormIntegratedRes).GetTypeInfo().Assembly);
                }

                return FormIntegratedRes.resourceManager;
            }
        }
    }
}