//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DayAttackKind {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DayAttackKind() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.DayAttackKind", typeof(DayAttackKind).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空撃.
        /// </summary>
        public static string AirAttack {
            get {
                return ResourceManager.GetString("AirAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空母カットイン.
        /// </summary>
        public static string CutinAirAttack {
            get {
                return ResourceManager.GetString("CutinAirAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カットイン(主砲/徹甲).
        /// </summary>
        public static string CutinMainAP {
            get {
                return ResourceManager.GetString("CutinMainAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カットイン(主砲/主砲).
        /// </summary>
        public static string CutinMainMain {
            get {
                return ResourceManager.GetString("CutinMainMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カットイン(主砲/電探).
        /// </summary>
        public static string CutinMainRadar {
            get {
                return ResourceManager.GetString("CutinMainRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カットイン(主砲/副砲).
        /// </summary>
        public static string CutinMainSub {
            get {
                return ResourceManager.GetString("CutinMainSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爆雷攻撃.
        /// </summary>
        public static string DepthCharge {
            get {
                return ResourceManager.GetString("DepthCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連続射撃.
        /// </summary>
        public static string DoubleShelling {
            get {
                return ResourceManager.GetString("DoubleShelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 揚陸攻撃(内火艇).
        /// </summary>
        public static string LandingAmphibious {
            get {
                return ResourceManager.GetString("LandingAmphibious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 揚陸攻撃(大発動艇).
        /// </summary>
        public static string LandingDaihatsu {
            get {
                return ResourceManager.GetString("LandingDaihatsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 揚陸攻撃(大発戦車).
        /// </summary>
        public static string LandingDaihatsuTank {
            get {
                return ResourceManager.GetString("LandingDaihatsuTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 揚陸攻撃(特大発動艇).
        /// </summary>
        public static string LandingTokuDaihatsu {
            get {
                return ResourceManager.GetString("LandingTokuDaihatsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 揚陸攻撃(特大発戦車).
        /// </summary>
        public static string LandingTokuDaihatsuTank {
            get {
                return ResourceManager.GetString("LandingTokuDaihatsuTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レーザー攻撃.
        /// </summary>
        public static string Laser {
            get {
                return ResourceManager.GetString("Laser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常攻撃.
        /// </summary>
        public static string NormalAttack {
            get {
                return ResourceManager.GetString("NormalAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロケット砲撃.
        /// </summary>
        public static string Rocket {
            get {
                return ResourceManager.GetString("Rocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海空立体攻撃.
        /// </summary>
        public static string SeaAirMultiAngle {
            get {
                return ResourceManager.GetString("SeaAirMultiAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 砲撃.
        /// </summary>
        public static string Shelling {
            get {
                return ResourceManager.GetString("Shelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 長門、いい？ いくわよ！ 主砲一斉射ッ！.
        /// </summary>
        public static string SpecialMutsu {
            get {
                return ResourceManager.GetString("SpecialMutsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一斉射かッ…胸が熱いな！.
        /// </summary>
        public static string SpecialNagato {
            get {
                return ResourceManager.GetString("SpecialNagato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nelson Touch.
        /// </summary>
        public static string SpecialNelson {
            get {
                return ResourceManager.GetString("SpecialNelson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷撃.
        /// </summary>
        public static string Torpedo {
            get {
                return ResourceManager.GetString("Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 瑞雲立体攻撃.
        /// </summary>
        public static string ZuiunMultiAngle {
            get {
                return ResourceManager.GetString("ZuiunMultiAngle", resourceCulture);
            }
        }
    }
}
