//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogShipSimulationWpf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogShipSimulationWpf() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.DialogShipSimulationWpf", typeof(DialogShipSimulationWpf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜命中項.
        /// </summary>
        public static string AswAccuracy {
            get {
                return ResourceManager.GetString("AswAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜ダメージ.
        /// </summary>
        public static string AswDamage {
            get {
                return ResourceManager.GetString("AswDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜命中率.
        /// </summary>
        public static string AswHitRate {
            get {
                return ResourceManager.GetString("AswHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜力.
        /// </summary>
        public static string AswPower {
            get {
                return ResourceManager.GetString("AswPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼砲撃命中項.
        /// </summary>
        public static string DayShellingAccuracy {
            get {
                return ResourceManager.GetString("DayShellingAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼砲撃ダメージ.
        /// </summary>
        public static string DayShellingDamage {
            get {
                return ResourceManager.GetString("DayShellingDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼砲撃命中率.
        /// </summary>
        public static string DayShellingHitRate {
            get {
                return ResourceManager.GetString("DayShellingHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼砲撃力.
        /// </summary>
        public static string DayShellingPower {
            get {
                return ResourceManager.GetString("DayShellingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 照明弾.
        /// </summary>
        public static string Flare {
            get {
                return ResourceManager.GetString("Flare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜偵.
        /// </summary>
        public static string NightRecon {
            get {
                return ResourceManager.GetString("NightRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜砲撃命中項.
        /// </summary>
        public static string NightShellingAccuracy {
            get {
                return ResourceManager.GetString("NightShellingAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜砲撃ダメージ.
        /// </summary>
        public static string NightShellingDamage {
            get {
                return ResourceManager.GetString("NightShellingDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜砲撃命中率.
        /// </summary>
        public static string NightShellingHitRate {
            get {
                return ResourceManager.GetString("NightShellingHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜砲撃力.
        /// </summary>
        public static string NightShellingPower {
            get {
                return ResourceManager.GetString("NightShellingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 探照灯.
        /// </summary>
        public static string Searchlight {
            get {
                return ResourceManager.GetString("Searchlight", resourceCulture);
            }
        }
    }
}
