//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FleetPositionDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FleetPositionDetail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.FleetPositionDetail", typeof(FleetPositionDetail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第2艦隊.
        /// </summary>
        public static string Escort {
            get {
                return ResourceManager.GetString("Escort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第2艦隊旗艦.
        /// </summary>
        public static string EscortFlag {
            get {
                return ResourceManager.GetString("EscortFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第1艦隊.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第1艦隊旗艦.
        /// </summary>
        public static string MainFlag {
            get {
                return ResourceManager.GetString("MainFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警戒陣警戒艦.
        /// </summary>
        public static string VanguardBottom {
            get {
                return ResourceManager.GetString("VanguardBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警戒陣旗艦.
        /// </summary>
        public static string VanguardFlag {
            get {
                return ResourceManager.GetString("VanguardFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警戒陣主力艦.
        /// </summary>
        public static string VanguardTop {
            get {
                return ResourceManager.GetString("VanguardTop", resourceCulture);
            }
        }
    }
}
