//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormationType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormationType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.FormationType", typeof(FormationType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輪形陣.
        /// </summary>
        public static string Diamond {
            get {
                return ResourceManager.GetString("Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複縦陣.
        /// </summary>
        public static string DoubleLine {
            get {
                return ResourceManager.GetString("DoubleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梯形陣.
        /// </summary>
        public static string Echelon {
            get {
                return ResourceManager.GetString("Echelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一警戒航行序列.
        /// </summary>
        public static string FirstPatrolFormation {
            get {
                return ResourceManager.GetString("FirstPatrolFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第四警戒航行序列.
        /// </summary>
        public static string FourthPatrolFormation {
            get {
                return ResourceManager.GetString("FourthPatrolFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単横陣.
        /// </summary>
        public static string LineAbreast {
            get {
                return ResourceManager.GetString("LineAbreast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単縦陣.
        /// </summary>
        public static string LineAhead {
            get {
                return ResourceManager.GetString("LineAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第二警戒航行序列.
        /// </summary>
        public static string SecondPatrolFormation {
            get {
                return ResourceManager.GetString("SecondPatrolFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第三警戒航行序列.
        /// </summary>
        public static string ThirdPatrolFormation {
            get {
                return ResourceManager.GetString("ThirdPatrolFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警戒陣.
        /// </summary>
        public static string Vanguard {
            get {
                return ResourceManager.GetString("Vanguard", resourceCulture);
            }
        }
    }
}
