// <auto-generated />
using ElectronicObserverDatabase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElectronicObserverDatabase.Migrations.UserData
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20191228121531_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("ElectronicObserverDatabase.Models.UserShipData", b =>
                {
                    b.Property<int>("DropId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShipId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DropId");

                    b.HasIndex("DropId")
                        .IsUnique();

                    b.ToTable("UserShipData");
                });
#pragma warning restore 612, 618
        }
    }
}
