//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Data.ShipGroup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExpressionDataRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExpressionDataRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Data.ShipGroup.ExpressionDataRes", typeof(ExpressionDataRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base AA.
        /// </summary>
        internal static string AABase {
            get {
                return ResourceManager.GetString("AABase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AA Remaining.
        /// </summary>
        internal static string AARemain {
            get {
                return ResourceManager.GetString("AARemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total AA.
        /// </summary>
        internal static string AATotal {
            get {
                return ResourceManager.GetString("AATotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerial Power.
        /// </summary>
        internal static string AirBattlePower {
            get {
                return ResourceManager.GetString("AirBattlePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Power.
        /// </summary>
        internal static string AircraftPower {
            get {
                return ResourceManager.GetString("AircraftPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft #1 Percentage.
        /// </summary>
        internal static string AircraftRate1 {
            get {
                return ResourceManager.GetString("AircraftRate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft #2 Percentage.
        /// </summary>
        internal static string AircraftRate2 {
            get {
                return ResourceManager.GetString("AircraftRate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft #3 Percentage.
        /// </summary>
        internal static string AircraftRate3 {
            get {
                return ResourceManager.GetString("AircraftRate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft #4 Percentage.
        /// </summary>
        internal static string AircraftRate4 {
            get {
                return ResourceManager.GetString("AircraftRate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft #5 Percentage.
        /// </summary>
        internal static string AircraftRate5 {
            get {
                return ResourceManager.GetString("AircraftRate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Total Percentage.
        /// </summary>
        internal static string AircraftRateTotal {
            get {
                return ResourceManager.GetString("AircraftRateTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft #1.
        /// </summary>
        internal static string AircraftSlot1 {
            get {
                return ResourceManager.GetString("AircraftSlot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft #2.
        /// </summary>
        internal static string AircraftSlot2 {
            get {
                return ResourceManager.GetString("AircraftSlot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft #3.
        /// </summary>
        internal static string AircraftSlot3 {
            get {
                return ResourceManager.GetString("AircraftSlot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft #4.
        /// </summary>
        internal static string AircraftSlot4 {
            get {
                return ResourceManager.GetString("AircraftSlot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft #5.
        /// </summary>
        internal static string AircraftSlot5 {
            get {
                return ResourceManager.GetString("AircraftSlot5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft Total.
        /// </summary>
        internal static string AircraftTotal {
            get {
                return ResourceManager.GetString("AircraftTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album No..
        /// </summary>
        internal static string AlbumNo {
            get {
                return ResourceManager.GetString("AlbumNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipments.
        /// </summary>
        internal static string AllSlotMaster {
            get {
                return ResourceManager.GetString("AllSlotMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo.
        /// </summary>
        internal static string Ammo {
            get {
                return ResourceManager.GetString("Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Ammo.
        /// </summary>
        internal static string AmmoMax {
            get {
                return ResourceManager.GetString("AmmoMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ammo Percentage.
        /// </summary>
        internal static string AmmoRate {
            get {
                return ResourceManager.GetString("AmmoRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Armor.
        /// </summary>
        internal static string ArmorBase {
            get {
                return ResourceManager.GetString("ArmorBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor Remaining.
        /// </summary>
        internal static string ArmorRemain {
            get {
                return ResourceManager.GetString("ArmorRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Armor.
        /// </summary>
        internal static string ArmorTotal {
            get {
                return ResourceManager.GetString("ArmorTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base ASW.
        /// </summary>
        internal static string ASWBase {
            get {
                return ResourceManager.GetString("ASWBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASW Power.
        /// </summary>
        internal static string ASWPower {
            get {
                return ResourceManager.GetString("ASWPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total ASW.
        /// </summary>
        internal static string ASWTotal {
            get {
                return ResourceManager.GetString("ASWTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Bombers.
        /// </summary>
        internal static string BomberTotal {
            get {
                return ResourceManager.GetString("BomberTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equippable Categories.
        /// </summary>
        internal static string EquippableCategories {
            get {
                return ResourceManager.GetString("EquippableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Evasion.
        /// </summary>
        internal static string EvasionBase {
            get {
                return ResourceManager.GetString("EvasionBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Evasion.
        /// </summary>
        internal static string EvasionTotal {
            get {
                return ResourceManager.GetString("EvasionTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expansion Slot Equipment.
        /// </summary>
        internal static string ExpansionSlotMaster {
            get {
                return ResourceManager.GetString("ExpansionSlotMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp Next.
        /// </summary>
        internal static string ExpNext {
            get {
                return ResourceManager.GetString("ExpNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp to Next Remodel.
        /// </summary>
        internal static string ExpNextRemodel {
            get {
                return ResourceManager.GetString("ExpNextRemodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp Total.
        /// </summary>
        internal static string ExpTotal {
            get {
                return ResourceManager.GetString("ExpTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Firepower.
        /// </summary>
        internal static string FirePowerBase {
            get {
                return ResourceManager.GetString("FirePowerBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firepower Remaining.
        /// </summary>
        internal static string FirePowerRemain {
            get {
                return ResourceManager.GetString("FirePowerRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Firepower.
        /// </summary>
        internal static string FirePowerTotal {
            get {
                return ResourceManager.GetString("FirePowerTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet Index.
        /// </summary>
        internal static string FleetWithIndex {
            get {
                return ResourceManager.GetString("FleetWithIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        internal static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Fuel.
        /// </summary>
        internal static string FuelMax {
            get {
                return ResourceManager.GetString("FuelMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Percentage.
        /// </summary>
        internal static string FuelRate {
            get {
                return ResourceManager.GetString("FuelRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current HP.
        /// </summary>
        internal static string HPCurrent {
            get {
                return ResourceManager.GetString("HPCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max HP.
        /// </summary>
        internal static string HPMax {
            get {
                return ResourceManager.GetString("HPMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP Percentage.
        /// </summary>
        internal static string HPRate {
            get {
                return ResourceManager.GetString("HPRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string IsLocked {
            get {
                return ResourceManager.GetString("IsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked By Equipment.
        /// </summary>
        internal static string IsLockedByEquipment {
            get {
                return ResourceManager.GetString("IsLockedByEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        internal static string IsMarried {
            get {
                return ResourceManager.GetString("IsMarried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base LOS.
        /// </summary>
        internal static string LOSBase {
            get {
                return ResourceManager.GetString("LOSBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total LOS.
        /// </summary>
        internal static string LOSTotal {
            get {
                return ResourceManager.GetString("LOSTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Luck.
        /// </summary>
        internal static string LuckBase {
            get {
                return ResourceManager.GetString("LuckBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luck Remaining.
        /// </summary>
        internal static string LuckRemain {
            get {
                return ResourceManager.GetString("LuckRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Luck.
        /// </summary>
        internal static string LuckTotal {
            get {
                return ResourceManager.GetString("LuckTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Aircraft #1.
        /// </summary>
        internal static string MasterAircraft1 {
            get {
                return ResourceManager.GetString("MasterAircraft1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Aircraft #2.
        /// </summary>
        internal static string MasterAircraft2 {
            get {
                return ResourceManager.GetString("MasterAircraft2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Aircraft #3.
        /// </summary>
        internal static string MasterAircraft3 {
            get {
                return ResourceManager.GetString("MasterAircraft3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Aircraft #4.
        /// </summary>
        internal static string MasterAircraft4 {
            get {
                return ResourceManager.GetString("MasterAircraft4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Aircraft #5.
        /// </summary>
        internal static string MasterAircraft5 {
            get {
                return ResourceManager.GetString("MasterAircraft5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Aircraft Total.
        /// </summary>
        internal static string MasterAircraftTotal {
            get {
                return ResourceManager.GetString("MasterAircraftTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterID.
        /// </summary>
        internal static string MasterID {
            get {
                return ResourceManager.GetString("MasterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarity.
        /// </summary>
        internal static string MasterRarity {
            get {
                return ResourceManager.GetString("MasterRarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Speed.
        /// </summary>
        internal static string MasterSpeed {
            get {
                return ResourceManager.GetString("MasterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Reading.
        /// </summary>
        internal static string NameReading {
            get {
                return ResourceManager.GetString("NameReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name With Class.
        /// </summary>
        internal static string NameWithClass {
            get {
                return ResourceManager.GetString("NameWithClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Battle Power.
        /// </summary>
        internal static string NightBattlePower {
            get {
                return ResourceManager.GetString("NightBattlePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship ID After Remodel.
        /// </summary>
        internal static string RemodelAfterShipID {
            get {
                return ResourceManager.GetString("RemodelAfterShipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship ID Before Remodel.
        /// </summary>
        internal static string RemodelBeforeShipID {
            get {
                return ResourceManager.GetString("RemodelBeforeShipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Fuel.
        /// </summary>
        internal static string RepairFuel {
            get {
                return ResourceManager.GetString("RepairFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock ID.
        /// </summary>
        internal static string RepairingDockID {
            get {
                return ResourceManager.GetString("RepairingDockID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Steel.
        /// </summary>
        internal static string RepairSteel {
            get {
                return ResourceManager.GetString("RepairSteel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Time.
        /// </summary>
        internal static string RepairTime {
            get {
                return ResourceManager.GetString("RepairTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Area.
        /// </summary>
        internal static string SallyArea {
            get {
                return ResourceManager.GetString("SallyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelling Power.
        /// </summary>
        internal static string ShellingPower {
            get {
                return ResourceManager.GetString("ShellingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipID.
        /// </summary>
        internal static string ShipID {
            get {
                return ResourceManager.GetString("ShipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Type.
        /// </summary>
        internal static string ShipType {
            get {
                return ResourceManager.GetString("ShipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment #1.
        /// </summary>
        internal static string SlotMaster1 {
            get {
                return ResourceManager.GetString("SlotMaster1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment #2.
        /// </summary>
        internal static string SlotMaster2 {
            get {
                return ResourceManager.GetString("SlotMaster2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment #3.
        /// </summary>
        internal static string SlotMaster3 {
            get {
                return ResourceManager.GetString("SlotMaster3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment #4.
        /// </summary>
        internal static string SlotMaster4 {
            get {
                return ResourceManager.GetString("SlotMaster4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment #5.
        /// </summary>
        internal static string SlotMaster5 {
            get {
                return ResourceManager.GetString("SlotMaster5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slots Count.
        /// </summary>
        internal static string SlotSize {
            get {
                return ResourceManager.GetString("SlotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array Contains.
        /// </summary>
        internal static string StrArrayContains {
            get {
                return ResourceManager.GetString("StrArrayContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array Not Contains.
        /// </summary>
        internal static string StrArrayNotContains {
            get {
                return ResourceManager.GetString("StrArrayNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins With.
        /// </summary>
        internal static string StrBeginsWith {
            get {
                return ResourceManager.GetString("StrBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string StrContains {
            get {
                return ResourceManager.GetString("StrContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End With.
        /// </summary>
        internal static string StrEndWith {
            get {
                return ResourceManager.GetString("StrEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==.
        /// </summary>
        internal static string StrEquals {
            get {
                return ResourceManager.GetString("StrEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        internal static string StrLessEquals {
            get {
                return ResourceManager.GetString("StrLessEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string StrLessThan {
            get {
                return ResourceManager.GetString("StrLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        internal static string StrMoreEquals {
            get {
                return ResourceManager.GetString("StrMoreEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string StrMoreThan {
            get {
                return ResourceManager.GetString("StrMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Begins With.
        /// </summary>
        internal static string StrNotBeginsWith {
            get {
                return ResourceManager.GetString("StrNotBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Contains.
        /// </summary>
        internal static string StrNotContains {
            get {
                return ResourceManager.GetString("StrNotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not End With.
        /// </summary>
        internal static string StrNotEndWith {
            get {
                return ResourceManager.GetString("StrNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !=.
        /// </summary>
        internal static string StrNotEquals {
            get {
                return ResourceManager.GetString("StrNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Torpedo.
        /// </summary>
        internal static string TorpedoBase {
            get {
                return ResourceManager.GetString("TorpedoBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo Power.
        /// </summary>
        internal static string TorpedoPower {
            get {
                return ResourceManager.GetString("TorpedoPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torpedo Remaining.
        /// </summary>
        internal static string TorpedoRemain {
            get {
                return ResourceManager.GetString("TorpedoRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Torpedo.
        /// </summary>
        internal static string TorpedoTotal {
            get {
                return ResourceManager.GetString("TorpedoTotal", resourceCulture);
            }
        }
    }
}
