//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserverTypes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogShipSimulationWpf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogShipSimulationWpf() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserverTypes.Properties.DialogShipSimulationWpf", typeof(DialogShipSimulationWpf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜命中項.
        /// </summary>
        public static string LabelAswAccuracy {
            get {
                return ResourceManager.GetString("LabelAswAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜ダメージ (クリティカル).
        /// </summary>
        public static string LabelAswDamage {
            get {
                return ResourceManager.GetString("LabelAswDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜命中率.
        /// </summary>
        public static string LabelAswHitRate {
            get {
                return ResourceManager.GetString("LabelAswHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜力 (クリティカル).
        /// </summary>
        public static string LabelAswPower {
            get {
                return ResourceManager.GetString("LabelAswPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼砲撃命中項.
        /// </summary>
        public static string LabelDayShellingAccuracy {
            get {
                return ResourceManager.GetString("LabelDayShellingAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼砲撃ダメージ (クリティカル).
        /// </summary>
        public static string LabelDayShellingDamage {
            get {
                return ResourceManager.GetString("LabelDayShellingDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼砲撃命中率.
        /// </summary>
        public static string LabelDayShellingHitRate {
            get {
                return ResourceManager.GetString("LabelDayShellingHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼砲撃力 (クリティカル).
        /// </summary>
        public static string LabelDayShellingPower {
            get {
                return ResourceManager.GetString("LabelDayShellingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 照明弾.
        /// </summary>
        public static string LabelFlare {
            get {
                return ResourceManager.GetString("LabelFlare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜偵.
        /// </summary>
        public static string LabelNightRecon {
            get {
                return ResourceManager.GetString("LabelNightRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜砲撃命中項.
        /// </summary>
        public static string LabelNightShellingAccuracy {
            get {
                return ResourceManager.GetString("LabelNightShellingAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜砲撃ダメージ (クリティカル).
        /// </summary>
        public static string LabelNightShellingDamage {
            get {
                return ResourceManager.GetString("LabelNightShellingDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜砲撃命中率.
        /// </summary>
        public static string LabelNightShellingHitRate {
            get {
                return ResourceManager.GetString("LabelNightShellingHitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜砲撃力 (クリティカル).
        /// </summary>
        public static string LabelNightShellingPower {
            get {
                return ResourceManager.GetString("LabelNightShellingPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 探照灯.
        /// </summary>
        public static string LabelSearchlight {
            get {
                return ResourceManager.GetString("LabelSearchlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シナジー.
        /// </summary>
        public static string LabelSynergy {
            get {
                return ResourceManager.GetString("LabelSynergy", resourceCulture);
            }
        }
    }
}
